version: '3.8'

services:

  backend:
    build:
      context: ./services/backend-api/Qrbank

    container_name: qrbank-backend

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

      MYSQLHOST: ${MYSQLHOST}
      MYSQLPORT: ${MYSQLPORT}
      MYSQLDATABASE: ${MYSQLDATABASE}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      MAIL: ${MAIL}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    depends_on:
      - mysql

    restart: unless-stopped

  mysql:
    image: mysql:8.4

    container_name: qrbank-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root123

      MYSQL_DATABASE: ${MYSQLDATABASE}

      MYSQL_USER: ${MYSQLUSER}
      MYSQL_PASSWORD: ${MYSQLPASSWORD}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: unless-stopped
volumes:
  mysql_data: