spring.application.name=Qrbank
spring.r2dbc.url=r2dbc:mysql://localhost:3306/qrbank?serverTimezone=UTC
spring.r2dbc.username=root
spring.r2dbc.password=root123
jwt.secret=8qOaQgNgN6cOtQNPPIhnB8lzrQ2nC9bCm8S38swyoDA=
jwt.expiration=900000
jwt.refresh_expiration=604800000
