# =========================
# R2DBC (WebFlux - LOCAL)
# =========================
spring.r2dbc.url=r2dbc:mysql://localhost:3306/qrbank?serverTimezone=UTC
spring.r2dbc.username=obed
spring.r2dbc.password=15170

# =========================
# FLYWAY (LOCAL JDBC)
# =========================
spring.flyway.url=jdbc:mysql://localhost:3306/qrbank
spring.flyway.user=obed
spring.flyway.password=15170
