spring.application.name=Qrbank

# =========================
# R2DBC (WebFlux)
# =========================
spring.r2dbc.url=r2dbc:mysql://localhost:3306/qrbank?serverTimezone=UTC
spring.r2dbc.username=obed
spring.r2dbc.password=15170

# =========================
# JWT
# =========================
jwt.secret=8qOaQgNgN6cOtQNPPIhnB8lzrQ2nC9bCm8S38swyoDA=
jwt.expiration=900000
jwt.refresh_expiration=604800000

# =========================
# MYSQL - JDBC (Flyway use it)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/qrbank?serverTimezone=UTC
spring.datasource.username=obed
spring.datasource.password=15170
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# FLYWAY (MIGRATIONS)
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true


# =========================
# EMAIL - GMAIL SMTP
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akatsukia2itel@gmail.com
spring.mail.password=gfvexceiblunzpzm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =========================
# CONSUMER - KAFKA
# =========================

#spring.kafka.bootstrap-servers=localhost:9092

#spring.kafka.consumer.group-id=qrbank-notification
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#spring.kafka.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.json.trusted.packages=*
#spring.kafka.consumer.properties.spring.json.value.default.type=backend_api.Qrbank.kafka.LedgerTransactionConsumer