spring.r2dbc.url=r2dbc:mysql://host.docker.internal:3306/qrbank
spring.r2dbc.username=obed
spring.r2dbc.password=15170

spring.flyway.url=jdbc:mysql://host.docker.internal:3306/qrbank
spring.flyway.user=obed
spring.flyway.password=15170